name: Auto-approve Own PR
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, ready_for_review]
jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # 确保有写入权限
    steps:
      - name: Auto-approve PR
        uses: actions/github-script@v5
        with:
          script: |
            try {
              const author = github.context.payload.pull_request?.user?.login;
              console.log('Author:', author);
              if (author === ${{ secrets.OWN_USER_NAME }}) {
                await github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: github.context.payload.pull_request.number,
                  event: 'APPROVE'
                });
                console.log('PR approved successfully.');
              }
            } catch (error) {
              console.error('Error:', error);
              throw error;
            }
