name: Auto-approve Own PR
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, ready_for_review]
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: actions/github-script@v5
        with:
          script: |
            // 仅当 PR 作者是仓库拥有者时触发
            if (context.payload.pull_request.user.login === ${{ secrets.OWN_USER_NAME }}) {
              github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE'
              })
            }