name: publish-halo-store

on:
  release:
    types:
      - published

jobs:
  # 不是预览版本且名称不含beta时执行
  cd:
    uses: zsjy/reusable-workflows/.github/workflows/theme-cd.yaml@v3
    if: |
      !github.event.release.prerelease && 
      !contains(github.event.release.tag_name, 'beta')
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      app-id: app-HrMpM
      pnpm-version: 10
      node-version: 22

  # 若cd任务未执行，则此任务也不执行
  npm-publish:
    name: Npm Publish
    needs: cd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      # 编译资源文件，用于上传到npm
      - name: Build
        run: npm run build-res --tag=${{ github.event.release.tag_name }}

      - name: npm publish
        run: npm publish --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}